# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  - build

build_macos:
  stage: build
  tags:
    - macos
  script:
    - ./gradlew createIPA2
  artifacts:
    paths:
    - ios/build/robovm
  
